apiVersion: apps/v1
kind: Deployment
metadata:
  name: beacon-priorauth
  namespace: beacon
  labels:
    app: beacon-priorauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beacon-priorauth
  template:
    metadata:
      labels:
        app: beacon-priorauth
    spec:
      serviceAccountName: beacon-sa
      nodeSelector:
        node-group: beacon-llm
      containers:
        - name: priorauth-app
          image: 747675253087.dkr.ecr.us-west-2.amazonaws.com/beacon-priorauth:latest
          ports:
            - containerPort: 8000
          env:
            - name: S3_BUCKET
              value: "beacon-priorauthai-assets"
            - name: AWS_REGION
              value: "us-west-2"
            - name: BEDROCK_MODEL
              value: "amazon.nova-lite-v1:0"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
          readinessProbe:
            httpGet:
              path: /agent/policies
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /agent/policies
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30

      volumes: []
